/**
 * Build-time precompiler for AKADEMIKA prompts.
 *
 * Reads AKADEMIKA/ from disk ONCE at build time and emits
 * src/lib/compiled-prompts.generated.ts — a typed Record<string, string> keyed by
 * `${directionKey}__${discipline}`. Each value is the static module composition
 * (CORE → LANGUAGE → DISCIPLINE → PROJECT → GLOSSARY → EXAMPLES). The dynamic
 * ACTIVE CONFIG header is added per-request at runtime in assemble-prompt.server.ts,
 * so the runtime never touches the filesystem (works in a bundled serverless fn).
 *
 * Run via the npm pre-hooks (prebuild / prebuild:dev / predev) or directly:
 *   npx tsx scripts/precompile-prompts.ts
 *
 * The Python CLI (AKADEMIKA/assemble.py) is unaffected — it remains the local
 * authoring/inspection tool.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const ROOT = path.join(process.cwd(), "AKADEMIKA");
const OUT = path.join(process.cwd(), "src", "lib", "compiled-prompts.generated.ts");

// Glossary is shared across all combinations.
const GLOSSARY_REL = "glossary/ai_tr.tsv";

function banner(title: string): string {
  const bar = "═".repeat(67);
  return `\n${bar}\n║  ${title}\n${bar}\n`;
}

function readModule(relPath: string): string | null {
  const full = path.join(ROOT, relPath);
  if (!existsSync(full)) {
    console.warn(`[precompile] missing module: ${relPath} — skipping`);
    return null;
  }
  return readFileSync(full, "utf-8").replace(/\s+$/, "") + "\n";
}

/** Render a glossary .tsv into readable "src  →  tgt   # note" lines. */
function renderGlossary(relPath: string): string | null {
  const full = path.join(ROOT, relPath);
  if (!existsSync(full)) {
    console.warn(`[precompile] missing glossary: ${relPath} — skipping`);
    return null;
  }
  const rows = readFileSync(full, "utf-8")
    .split(/\r?\n/)
    .filter((line) => line.trim())
    .map((line) => line.split("\t"));

  const lines = rows.slice(1).map((row) => {
    const src = row[0] ?? "";
    const tgt = row[1] ?? "";
    const note = row[2] ?? "";
    let line = `  ${src}  →  ${tgt}`;
    if (note) line += `   # ${note}`;
    return line;
  });

  return (
    "GLOSSARY (binding — Tier 4; overrides preference)\n" + lines.join("\n") + "\n"
  );
}

/** Compose the static module body for one (direction × discipline × project).
 *  Null if a required module (core / language / discipline / project) is missing. */
function buildBody(
  directionKey: string,
  discipline: string,
  project: string,
): string | null {
  const core = readModule("core.md");
  const language = readModule(`language/${directionKey}.md`);
  const disciplineMod = readModule(`discipline/${discipline}.md`);
  const projectMod = readModule(`project/${project}.md`);
  if (!core || !language || !disciplineMod || !projectMod) return null;

  const parts: string[] = [
    banner("CORE") + core,
    banner("LANGUAGE MODULE") + language,
    banner("DISCIPLINE MODULE") + disciplineMod,
    banner("PROJECT MODULE") + projectMod,
  ];

  const glossary = renderGlossary(GLOSSARY_REL);
  if (glossary) parts.push(banner("GLOSSARY") + glossary);

  const examples = readModule(`examples/${directionKey}.md`);
  if (examples) parts.push(banner("EXAMPLES (direction-matched)") + examples);

  return parts.join("\n");
}

/** List "<name>" for every <name>.md in an AKADEMIKA subdirectory. */
function listKeys(subdir: string): string[] {
  return readdirSync(path.join(ROOT, subdir))
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.replace(/\.md$/, ""))
    .sort();
}

const directions = listKeys("language"); // e.g. ["en_tr", "tr_en"]
const disciplines = listKeys("discipline"); // e.g. ["medicine", "nlp"]
const projects = listKeys("project"); // e.g. ["thesis_q1"]

const compiled: Record<string, string> = {};
for (const direction of directions) {
  for (const discipline of disciplines) {
    for (const project of projects) {
      const body = buildBody(direction, discipline, project);
      if (body) compiled[`${direction}__${discipline}__${project}`] = body;
    }
  }
}

const fileHeader = `// AUTO-GENERATED by scripts/precompile-prompts.ts — DO NOT EDIT.
// Regenerated before every build/dev via the npm pre-hooks. Git-ignored.
//
// Holds the static module composition for each (direction × discipline). The
// dynamic ACTIVE CONFIG header is prepended at runtime in assemble-prompt.server.ts.

export const COMPILED_PROMPTS: Record<string, string> = {
`;

const entries = Object.entries(compiled)
  .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
  .join("\n");

writeFileSync(OUT, fileHeader + entries + "\n};\n", "utf-8");

const rel = path.relative(process.cwd(), OUT);
console.log(`[precompile] wrote ${Object.keys(compiled).length} prompt(s) → ${rel}`);
for (const key of Object.keys(compiled)) console.log(`  · ${key}`);
