/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangRegisterRouteImport } from './routes/$lang/register'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangProtectedRouteImport } from './routes/$lang/_protected'
import { Route as LangProtectedTranslateRouteImport } from './routes/$lang/_protected/translate'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangRegisterRoute = LangRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangProtectedRoute = LangProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => LangRoute,
} as any)
const LangProtectedTranslateRoute = LangProtectedTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => LangProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/translate': typeof LangProtectedTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/translate': typeof LangProtectedTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$lang/_protected': typeof LangProtectedRouteWithChildren
  '/$lang/login': typeof LangLoginRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_protected/translate': typeof LangProtectedTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/login'
    | '/register'
    | '/$lang/login'
    | '/$lang/register'
    | '/$lang/'
    | '/$lang/translate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/$lang'
    | '/$lang/login'
    | '/$lang/register'
    | '/$lang/translate'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/login'
    | '/register'
    | '/$lang/_protected'
    | '/$lang/login'
    | '/$lang/register'
    | '/$lang/'
    | '/$lang/_protected/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/register': {
      id: '/$lang/register'
      path: '/register'
      fullPath: '/$lang/register'
      preLoaderRoute: typeof LangRegisterRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_protected': {
      id: '/$lang/_protected'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangProtectedRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_protected/translate': {
      id: '/$lang/_protected/translate'
      path: '/translate'
      fullPath: '/$lang/translate'
      preLoaderRoute: typeof LangProtectedTranslateRouteImport
      parentRoute: typeof LangProtectedRoute
    }
  }
}

interface LangProtectedRouteChildren {
  LangProtectedTranslateRoute: typeof LangProtectedTranslateRoute
}

const LangProtectedRouteChildren: LangProtectedRouteChildren = {
  LangProtectedTranslateRoute: LangProtectedTranslateRoute,
}

const LangProtectedRouteWithChildren = LangProtectedRoute._addFileChildren(
  LangProtectedRouteChildren,
)

interface LangRouteChildren {
  LangProtectedRoute: typeof LangProtectedRouteWithChildren
  LangLoginRoute: typeof LangLoginRoute
  LangRegisterRoute: typeof LangRegisterRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangProtectedRoute: LangProtectedRouteWithChildren,
  LangLoginRoute: LangLoginRoute,
  LangRegisterRoute: LangRegisterRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
